kataras/iris

middleware/cors.go
The original code was ported from [cors](https://github.com/rs/cors) middelware to Iris.
=> Added support for CORS middleware

party.go
=> Fix the bug of stripSlashes

README.md, iris.go
=> Add donates to the top, I really thank you!

.github/ISSUE_TEMPLATE.md, README.md
=> Push the new LTS(Long Term Support) version

_examples/intermediate/flash-messages/main.go
=> If name has value, it will show "Empty name!!"

_examples/hello-world/main.go
I was getting this bug
command-line-arguments
./main.go:22: undefined: iris.Context
./main.go:29: undefined: iris.Map
It solves #672
=> Fixed Hello World example

core/host/proxy_test.go, core/router/api_builder.go
That's fixes [Issue #678](https://github.com/kataras/iris/issues/678).
=> Add GetReporter method for getting the Reporter. Fixes #678

sessions/sessions.go
Fixes up issue #698 .
The input of `decodeCookieValue` is tested in case of there is an empty string, so then its output really reflect the validity of the input.
It takes in consideration that underlying decoder can invalidate the cookie.
We'd love to see contributions!!!
Please attach an [issue](http://support.iris-go.com) link which your PR solves otherwise your work may be rejected.
=> Sessions: Test decoded cookie for empty strings

websocket/connection.go
=> Fixed fireOnLeave when connection is already closed

websocket/connection.go
=> Websocket: fixed memory leak on startPinger

websocket/server.go
some extra methods are added to websocket to extend the functionality
see related issue #793
=> Websocket: added GetTotalConnections, GetConnections and GetConnection

.github/CODEOWNERS, AUTHORS, HISTORY.md, cache/AUTHORS, sessions/AUTHORS, typescript/AUTHORS, websocket/AUTHORS
I'm voluntarily quiting the responsibility of Iris Author. I've been re-positioned as the new Lead Product Manager of the company I'm working for many years, which I accepted with honor. That's a very time consuming position I'm responsible to accomplish and deliver, therefore, I transfer all my rights back to @kataras and I resign from any copyrights over this project. My contribution clearly didn't make the difference but I owe a big "thank you" to Gerasimos for the chance he gave me, I did learn a lot of stuff lately. I hope the bests to you and iris. Thank you all.
=> Thank you!

_examples/websocket/connectionlist/main.go
As this file is an example, it could help people to learn golang pattern. So, i've added another way to get a clock signal. I've kept the original to show people 2 different ways.
> Please attach an [issue](https://github.com/kataras/iris/issues) link which your PR solves otherwise your work may be rejected.  
Should i really do an issue for a so small change ? (No problem if it got reject, i understand)
=> more example in example

websocket/connection.go
=> Websocket: added OnPing to Connection

core/router/path.go, view/amber.go
- Stored the args length on a variable instead of three consecutive calls to the len method on "toStringSlice" function;
- Improved readability on "toStringSlice" function;
- Fixed a bug on "URL", which all routes without parameters would not return the full uri (just the path);
- Fix issue: kataras#827
=> Fixed a bug on router/path

core/router/path.go, view/amber.go
Fixed issue https://github.com/kataras/iris/issues/830
=> Honux patch 2

sessions/config.go, sessions/cookie.go, sessions/sessions.go
Sample
```go
newSess := _session.Start(ctx)
_session.UpdateExpiration(ctx, -1) // fixed this
```
=> fix cookie expire equals to -1 when call UpdateExpiration

view/django.go
=> Add wrappers for Pongo's AsValue() and AsSaveValue()

websocket/server.go
=> Handle non-WS connections in WS handler with no panic

_examples/http_request/request-logger/main.go, middleware/logger/config.go, middleware/logger/logger.go
=> add more information for access log

HISTORY_ZH.md
=> Translation updates

_examples/http_request/request-logger/request-logger-file/main.go
=> fix the bug of lost argument in log function

README.md
Just a simple README correction
=> Fix article link

HISTORY_ID.md, README_ID.md
Hi @kataras, based on #796 , I'd like to contribute by adding README_ID.md file that represent Bahasa Indonesia. Please take a look! 😄
=> Add README_ID.md

README_JPN.md
Added README Japanese version.
Japanese Flag needs to be added to the other READMEs.
=> README_JPN added

FAQ.md
=> Fixed some minor grammar issues

README.md
=> Typo internally

websocket/server.go
https://github.com/kataras/iris/issues/1108
=> Fix panic error in concurrent calling with websocket.Connection.Emit() 

_examples/README_ZH.md
It's 100% translated as you are asking in #796.
=> README_ZH.md in _examples/

README.md
Hey, this PR improves upon the old English documentation. I am sure this small update will be much easier to understand.
=> Improved english documentation

_examples/orm/gorm/main.go
=> feat: gorm example

_examples/http-listening/listen-tls/main.go
=> NewProxy no work

configuration.go
=> Fix Structtag Tunneling

core/router/api_builder.go, core/router/path.go, core/router/path_test.go, middleware/README.md, middleware/i18n/i18n.go
=> #1399 [BUG]Can't set file server in subdomain with request path is "/"

_examples/README.md
=> WebAssembly spelling

hero/reflect.go
=> fix bug: abount dependency injection

context/context.go
=> modify:add stringToBytes

README_FR.md
Hi 👋 
Thank you for all your work this framework is awesome !
I created a French version of the Readme file
#796
=> French version of readme writen

_examples/mvc/overview/main.go
=> fix #1559 - remove not need colon

go.mod
I don't created a new Issue only wan't to use the last version to use some features.
=> Update go.mod : jet/v4.1.0

go.mod
=> Update Jet dep to 5.0.2

context/context.go
i open an issue #1642, and fixed it
=> #1642: add check the values array length, avoid panic: index out of range

sessions/sessiondb/redis/driver_goredis.go
fix the password of redis connection options
=> fix the password of redis connection options

context/context.go
=> fix: index of ReadJSONProtobuf options

core/host/proxy.go
ISSUE #1702 
PR #1703 
https://github.com/kataras/iris/pull/1703#issuecomment-764798192
=> udpate modifyProxiedRequest

README.md
=> Go into myapp folder after create it

core/host/proxy.go, core/host/proxy_test.go
=> bug fix #1741 #1744

_examples/mvc/hello-world/main.go, mvc/controller.go, mvc/controller_method_parser.go, mvc/mvc.go
To fix : [1737](https://github.com/kataras/iris/issues/1737)
=> add CustomPathWordFunc

context/application.go
issues: [https://github.com/kataras/iris/issues/1752](https://github.com/kataras/iris/issues/1752)
The mutex should have been unlocked, but it didn't
=> fix bug: #1752

context/context.go
=> fix: supper grpc and grpc web

go.mod
Fixes #1788 and #1780
If you can create the version 12.1.9 would be helpful, thx
=> Fix dependencies security issues

configuration.go
=> fix-comments

mvc/grpc.go
- Fires 404 HTTP Code when use gRPC strict mode
=> Fires 404 HTTP Code when gRPC strict mode enabled

_examples/auth/goth/main.go, _examples/mvc/vuejs-todo-mvc/src/todo/service.go, context/context.go
reduce slicing or map expansion
build initialization: https://go.dev/doc/effective_go#maps
=> Optimize: map or slice initialize allocation cap

README_VN.md
=> Translate README to Vietnamese

middleware/requestid/requestid_test.go
Add a test scenario for client sent request id header.
Issue: https://github.com/kataras/iris-premium/issues/20
=> Improve middleware/requestid test suite

sessions/session.go
Read how you can [contribute to the project](https://github.com/kataras/iris/blob/main/CONTRIBUTING.md).
=> FIX: Session.Destroy trigger map concurrency write

view/html.go
Sometime's ,We need change template dir.Like cms themes.So,Add `FS` func
=> add FS func in HTMLEngine

x/client/client.go
Read how you can [contribute to the project](https://github.com/kataras/iris/blob/main/CONTRIBUTING.md).
=> fix: close form file
