configuration.go, context_test.go, websocket.go
This is a fairly short patch which enables setting the config option for ReadTimeout via iris.Config.Websocket.ReadTimeout. The setting was added to go-websocket and is available in iris v6 but the change was not made in the v5 branch.
=> ReadTimeout setting added to go-websocket

view/django.go
This fixes [Issue #681](https://github.com/kataras/iris/issues/681). The problems was due to the template loader. A new template loader based on asset function getter has been implemented.
That code was used as test:
```go
package main
import (
"github.com/kataras/iris"
"github.com/kataras/iris/context"
"os"
)
var files = map[string]string{
"views/parent.html": `<!DOCTYPE html>
<html>
<head>
<title>Iris with Pongo2 template engine</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="cache-control" content="no-cache">
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>`,
"views/include.html": "Hello World !",
"views/child.html": `{% extends "parent.html" %}
{% block body %}
{% include …
```
=> Resolve Django `include` and `extends` tags problem

_examples/sessions/database/main.go, _examples/sessions/securecookie/main.go, _examples/sessions/standalone/main.go, sessions/database.go, sessions/provider.go, sessions/session.go, sessions/sessiondb/redis/database.go, sessions/sessions.go
This fixes up issue #692 .
What this PR adds:
- Restore expiration state of the sessions
- Add APIs to modify expire date
- Free the timer for the session destroy task
=> Fix up for sessions

middleware/i18n/i18n.go, vendor/github.com/Unknwon/i18n/i18n.go
* Add IETF matching method to vendor unkwon/i18n.
* Update i18n middleware to support RFC2616.
Solves [issue 696](https://github.com/kataras/iris/issues/696)
=> Update i18n middleware and toolkit methods to support IETF and RFC2616.

core/router/api_builder.go
According to your comments, we should remove the redundant slash before `relativePath`.
The previous code doesn't make sense... If so, the code below:
```go
api := app.Party("/api")
api.PartyFunc("/endpoint", func(route router.Party){
route.Get("/", someHandler)
})
```
will generate route `GET /endpoint` without prefix `/api`. 
The nested routes defined by `PartyFunc` will also be built unexpected.
=> bugfix: trim relative slash incorrectly in apiBuilder.Party

README.md
Your landing page seems quite unprofessional with these typos, another factor is the unnecessary bragging about your own framework but I did not bother to change that.
=> Fix some typos and grammar errors

iris.go
Fix incorrect host in "Now listening on:" message when using iris.Listener described in issue 757
=> Fix issue #757

view/django.go
#764 
I've added implementations to all 4 types defined above.
For instance, I only need to get `*pongo2.Value` and `*pongo2.Error`, but I think the others might be needed later.
=> Get pongo2's origin data type

core/router/api_builder.go
Fixup for UseGlobal call order. (Issue #778)
The `UseGlobal` handler just had to deported to the right slice for each new `Route`.
=> Fixup #778: UseGlobal call order

websocket/connection.go, websocket/server.go
=> Websocket: replaced time.Ticker with sleep for avoid memory leak

_examples/file-server/embedding-files-into-app/main_test.go, _examples/file-server/single-page-application/basic/main_test.go, _examples/file-server/single-page-application/embedded-single-page-application/main_test.go, _examples/mvc/cache/main.go, cache/LICENSE, cache/cache.go, cache/cache_test.go, cache/client/handler.go
Remove the old 'cache.WrapHandler' and keep the `cache.Handler` as documented only
=> make cache package to work across multi handlers.

websocket/server.go
websocket/server.leave() already has the code to remove a connection from the room, and in case it's the last connection in the room then also remove the room from the server rooms hash table.
however websocket/server.LeaveAll() duplicated the code to remove the connection from the room but without removing the room itself from the hash table if it's then empty. note that with the current architecture the rooms hash isn't used just for rooms but it's for every single websocket connection as well. so this makes the rooms hash ever growing with every connection and re-connection. (a hash key pointing to an empty array value)
this commit is to simply re-use server.leave() from server.LeaveAll(), it already fixes the ever-growing-hash issue.
=> websocket disconnect/leave-all-rooms should delete empty rooms as well otherwise rooms hash goes ever growing

Gopkg.toml
Version reference must be written in a version key. Otherwise, `dep ensure` can't solve dependency tree because «go.uuid» package doesn't have a branch «v1.2.0».
```
Solving failure: No versions of github.com/satori/go.uuid met constraints:
v1.2.0: Could not introduce github.com/satori/go.uuid@v1.2.0, as it is not allowed by constraints from the following projects:
v1.2.0 from github.com/kataras/iris@dev
v1.2.0 from github.com/kataras/iris@dev
v1.1.0: Could not introduce github.com/satori/go.uuid@v1.1.0, as it is not allowed by constraints from the following projects:
v1.2.0 from github.com/kataras/iris@dev
v1.2.0 from github.com/kataras/iris@dev
v1.0.0: Could not introduce github.com/satori/go.uuid@v1.0.0, as it is not allowed by constraints from the following projects:
v1.2.0 from …
```
=> Fix dep dependency

_examples/miscellaneous/recover/main.go
Corrected spelling from simmilate to simulate
=> corrected spelling for example docs

_examples/experimental-handlers/cors/simple/main.go, _examples/routing/fallback-handlers/main.go, _examples/routing/route-state/main.go, context/application.go, context/context.go, core/router/api_builder.go, core/router/fallback_stack.go, core/router/fallback_stack_test.go, core/router/handler.go, core/router/party.go, core/router/router.go, core/router/router_test.go, mvc/mvc.go
Fixes #884 
This PR adds features that prepares solution for #884. The solution will be implemented to fix up iris-contrib/middleware#32 and will use these features:
- A Fallback handler stack that allows to run handlers in that case which no route is not found,
- Adding use cases for example: _examples/experimental-handlers/cors/simple/main.go
Plus, for tests there are:
- An example for using Fallback handlers in _examples/routing/fallback-handlers,
- Go tests in core/router,
- A correction of the example: _examples/routing/route-state.
=> Fallback handlers

_examples/routing/fallback-handlers/main.go
This is continuation of PR #909  .
Something had been forgotten.
=> Add a missing call for `fallbackHandler`

cache/browser.go, cache/browser_test.go, cache/cache.go, cache/cache_test.go, context/context.go, iris.go
New:
- `cache.StaticCache` (and `iris.StaticCache` shortcut like the rest)
Re-write but keep compatibility with the server-side no-catching: 
- `cache.NoCache` (and `iris.NoCache` shortcut like the rest)
Tests:
- `kataras/iris/cache/browser_test.go` for `StaticCache`, `NoCache` and `Cache304`
Code Guidelines of the Iris project are followed. 
Branch: **dev** , push to master whenever you release the next version @kataras.
=> Add some useful cache middlewares for client (i.e browser) catching

core/router/handler.go
Fix open redirect by using strings.Trim.
Another option would be to use path.Clean similar to here, but I'm unsure of side effects that may have for this use case: https://github.com/golang/go/blob/master/src/net/http/server.go#L2034
See a PoC of this issue with this link: https://iris-go.com//google.com/
=> Fix open redirect

sessions/cookie.go, sessions/sessions.go
=> fix when destroy session can't remove cookie in subdomain

websocket/connection.go
=> Websocket: added OnPong to Connection #986

_examples/experimental-handlers/csrf/views/user/signup.html
=> Fix Typo in CSRF Example signup.html

_examples/experimental-handlers/jwt/main.go
Not sure if this sentence is right 
`// iris provides some basic middleware, most for your learning curve.`
Maybe you meant something like
` // iris provides some basic middleware to help newcomers understand the concepts.`
But I wasn't sure so I left the sentence alone (exepct for the typo lol)
=> Fixed Some Typos

sessions/lifetime.go, sessions/sessiondb/redis/service/service.go
1. lifetime.Time not updated on expiration shift
2. redis service.TTL() return values were incorrect and incompatible wtih its consumers such as redis database.Acquire(); this fix re-aligns the return values so:
- hasExpiration means there's a ttl value (i.e. > -1)
- found means the key is found, i.e. not(redis cmd error || ttl expired)
3. redis service.getKeysConn() previously returned keys as is from scanning the db
- inside getKeysConn() it scans redis with "r.Config.Prefix+prefix"
- previously it returned the found keys as is
- then UpdateTTLMany() would call updateTTLConn() with such keys
- and updateTTLConn() would again perform redis expire with "r.Config.Prefix+key"
- this causes the redis expire to always fail as the call to redis expire would be with duplicated prefixes
- with …
=> various fixes on redis as sessions db

configuration.go
`iris.YAML("myconfig.tml")` -> `iris.TOML("myconfig.tml")`
=> Fixed typo in comment

README.md
the example in the README.md is not right.
```go
app.Get("/users/{id:int64}", func(ctx iris.Context) {
id, _ := ctx.Params().GetUint64("id")
ctx.Writef("User with ID: %d", id)
})
```
change int64 to int,`/users/{id:int}`
```go
// However, this one will match /user/john/ and also /user/john/send.
app.Post("/user/{name:string}/{action:path}", func(ctx iris.Context) {
name := ctx.Params().Get("name")
action := ctx.Params().Get("action")
message := name + " is " + action
ctx.WriteString(message)
})
```
but `/user/john/` didn't match
=> update README.md example

cache/entry/entry.go
Currently, the body of a cache entry is set to the `chunks` of a request recorder.
```
body := recorder.Body() // <- recorder.chunks (which is reused)
e.response.body = body
```
However recorders are reused. If now a recorder is being reused and a cache entry points to a slice of the same array that is used to record the new request the cache entry is overwritten thereby corrupting the cache.
We need to copy the body to avoid this and make the cache entry immutable.
=> Fix cache corruption due to recorder reuse

README.md
the previous link  will be automatically appended to `https://github.com/kataras/iris/` and thus get a wrong direction
=> Fix link for httpexpect in README

HISTORY.md, VERSION, _examples/routing/http-errors/main.go, context/context.go, context/problem.go, doc.go, go19.go, iris.go
- Implements: https://github.com/kataras/iris/issues/1335
- Wiki: https://github.com/kataras/iris/wiki/Routing-error-handlers#the-problem-type
Example Code:
```go
func newProductProblem(productName, detail string) iris.Problem {
return iris.NewProblem().
// The type URI, if relative it automatically convert to absolute.
Type("/product-error"). 
// The title, if empty then it gets it from the status code.
Title("Product validation problem").
// Any optional details.
Detail(detail).
// The status error code, required.
Status(iris.StatusBadRequest).
// Any custom key-value pair.
Key("productName", productName)
// Optional cause of the problem, chain of Problems.
// .Cause(other iris.Problem)
}
func fireProblem(ctx iris.Context) {
ctx.Problem(newProductProblem("product name", "problem error …
```
=> Problem Details for HTTP APIs (v11.2.5)

mvc/controller_method_parser.go, mvc/controller_test.go
I found there has some little bug in the controller_method_parser.go
the bug is: if someone uses the code like this:
func (cc *HelloWorld) GetInfoXYT()
We can't create the Url that he wants.
We lost the T, our URL is: info/x/y
Cause I found the comment in this scope,
Like this:// it doesn't count the last uppercase 
And I think the author tries to append the lastest Code, but the last append is
words = append(words, s[start:end])
You know, If the string is GetInfoXYT the end index is the same as the start, so we lost the T.
I think this processing mode can not be accepted, so I try to fix this.
> Please attach an [issue](https://github.com/kataras/iris/issues) link which your PR solves …
=> Fix bug:about the MVC package route binding

_examples/file-server/basic/main.go, _examples/file-server/basic/main_test.go, core/router/api_builder.go
When I use file-server like this
```
v1 := app.Party("/aa/bb")
v1.HandleDir(/static, "./assets", iris.DirOptions{
IndexName: "/index.html",
Gzip: false,
ShowList: false,
})
```
and I request `http://localhost:8080/aa/bb/static` or `http://localhost:8080/aa/bb/cc/static/index.html`,
it will be 404 NOT FOUND.
Because the modified line will create a route `/aa/bb/aa/bb/static` which expected `/aa/bb/static`
Thanks for your consideration.
=> Modify core/router/api_builder.go

hero/func_result.go
The original URL is no longer accessible
=> fix: fix a comment error

README_ZH.md
Chinese translation for README.md
Rel to : #796
=> Chinese translate of README.md

NOTICE, _examples/view/template_django_0/main.go, go.mod, view/django.go
When this is fixed: https://github.com/flosch/pongo2-addons/issues/8 this PR should be merged to master.
Update: the authors are not as active there as here, so we just updated our iris-contrib/pongo2-addons with path suffix of /v4. Previous versions should work as usual.
=> Update pongo2 to version 4

_examples/mvc/error-handler-preflight/main.go
=> [fix _examples] response.timestamp not appear in correct request.

core/host/proxy.go, core/host/proxy_test.go
=> update host.ProxyHandler to compatiable with different hosts in target url and request host

core/router/fs.go
1. add `DirOptions.ShowHidden` option to show hidden files  or directories or not
2. modify DirList's default html format
- use `<div>` instead of `<pre>`
- use `<ul>` and `<li>` for file/directory list
- add a link to parent directory
- display current directory
- display file mode string
=> modifiy DirList's default html format

core/host/supervisor.go
Resolves https://github.com/kataras/iris/issues/1804
=> Fix panic on macos when passing a certificate as []byte to iris.TLS()

context/request_params.go
fix the invalid format of Context.RequestParams.Get() when the value is not string type, issue of https://github.com/kataras/iris/issues/1859
=> fix the invalid format of Context.RequestParams.Get() when the value is not string type

middleware/accesslog/accesslog.go
fix the issue of [accesslog closing the default writer os.Stdout by SetOutput() method](https://github.com/kataras/iris/issues/1862)
=> fix the issue of accesslog closing the default writer os.Stdout by SetOutput() method

configuration.go
Method `Configuration.GetLogLevel` must return LogLevel
=> Method Configuration.GetLogLevel returns LogLevel

_examples/logging/request-logger/accesslog/main.go
There're some bugs in lestrrat-go
Detail:  https://github.com/iproj/file-rotatelogs/issues/1
=> lestrrat-go -> iproj

context/configuration.go
Fix comments in `configuration.go`
=> fix comments

core/netutil/ip.go, core/netutil/ip_test.go
This fixes #2003
- fixing incorrect IP comparison. `unsafeCompare` was comparing between converted IP address with literal unconverted IP string.
- `IPInRange` should be both inclusive to accommodate /32 private subnet additions
- added more tests
=> Fix ctx.RemoteAddr() with multiple IP addresses value

hero/binding.go
For faster execution,
use strconv.Itoa rather than fmt.Sprintf to convert an integer to string,
remove if statement in loop.
=> hero: optimize *binding'String

context/response_recorder.go, context/response_writer.go, view/jet.go
From the Go docs:
> "If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/Cw_wnqYzemu
=> Remove redundant nil check

go.mod
As part of the upgrade to Go 1.21, the Go toolchain now requires the
`go` directive to match the maximum Go version in use in dependencies.
This leads to any transitive dependency on this library to result in a
requirement of the consuming project moving to Go 1.21.
Although in a lot of cases this may not be as problematic, it forces
consumers to migrate, which we don't need to do in this case.
This also requires we bump jwt and httpexpect dependencies, as they've
downgraded, too.
---
As discussed in https://github.com/deepmap/oapi-codegen/issues/1221 and related change in https://github.com/gofiber/fiber/pull/2614. See also https://github.com/golang/go/issues/62409
Draft until below are merged:
- https://github.com/kataras/jwt/pull/17
- https://github.com/iris-contrib/httpexpect/pull/1
=> Downgrade Go version requirement to 1.20

core/router/TestUseRouterParentDisallow_fuzz_test.go
Issue #2209 recommended the adoption of fuzz drivers in this project to continuously enhance its robustness and reliability. We use this fuzz driver to successfully discover bugs #1967 #1968 #2215 #2216 . We believe our fuzz driver will probably find more bugs in the future, and now we would like to share our fuzz driver with iris project in order to help iris find potential bugs.
=> add fuzz driver based on TestUseRouterParentDisallow

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
This PR fixes the CI warning "Restore cache failed: Dependencies file is not found in /home/runner/work/iris/iris. Supported file pattern: go.sum":
`setup-go` action has caching. But for enabling it's needed to checkout code first.
Additionally, the PR updates `checkout` action to v4.
=> chore: enable caching for CI

core/errgroup/errgroup.go
A small code refactoring.
`len(g.children) > 0` is redundant because `range` already skips empty slice.
=> errgroup: remove redundant `len` check

README_AR.md
Hi, given the growing interest in Go and web development within Arabic-speaking communities, an Arabic version could help more developers easily understand and engage with the framework.
Proposed Changes:
- Translate the README.md file into Arabic and add it as README_AR.md.
Related to [issue #796](https://github.com/kataras/iris/issues/796)
=> Add Arabic Translation for README.md
